### ISSUE TITLE
latest version of steam deck tools is 0.5.47

### ISSUE THREAD

**Issue by lamiska** [CelesteHeartsong/SteamDeckAutomatedInstall#2]
hi i reall like your scripts however it installs too old steam deck tools version

**Comment by CelesteHeartsong** [comment]
Thank you!

I'm currently working on a method to install the later versions of SteamDeckTools.

After 5.31, telemetry was introduced into the tooling, and I want to make enabling/disabling this telemetry an option during the script running.

Once I have that in place I'll update to the latest version of SteamDeckTools

**Comment by CelesteHeartsong** [comment]
SteamDeckTools has now been updated to 5.47 in the script, along with a dialog to allow users to choose whether to allow error reporting and telemetry gathering.

https://github.com/CelesteHeartsong/SteamDeckAutomatedInstall/releases/tag/v3.3
